In [1]:
from tensorflow.keras import backend as K  # type: ignore
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' # delete alert message from Tensorflow
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array  # type: ignore
import numpy as np

2024-04-15 11:02:06.624185: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
def dice_coef(y_true, y_pred, smooth=1e-6):
    y_true = K.cast(y_true, 'float32')
    y_pred = K.cast(y_pred, 'float32')
    
    inputs = K.flatten(y_pred)
    targets = K.flatten(y_true)

    targets = K.expand_dims(targets, axis=-1)
    inputs = K.expand_dims(inputs, axis=-1)

    intersection = K.sum(targets * inputs)
    return (2*intersection + smooth) / (K.sum(targets) + K.sum(inputs) + smooth)

def dice_coeff_multiclass(y_pred, y_true):
    num_class_pred = len(np.unique(y_pred))
    num_class_true = len(np.unique(y_true))
    if num_class_pred != num_class_true:
        return print("Error")
    else :
        num_class = np.unique(y_pred)

    el_unique = []
    for el in num_class:
        el_unique.append(el)

    dice_mean = []

    for value in el_unique:
        binary_pred = np.copy(y_pred)
        binary_pred[y_pred == value] = 0
        binary_pred[y_pred != value] = 1

        binary_true = np.copy(y_true)
        binary_true[y_true == value] = 0
        binary_true[y_true != value] = 1

        dice_mean.append(dice_coef(binary_true, binary_pred).numpy())

    return np.mean(dice_mean)


In [3]:
y_true = np.array([[3, 1, 1],
                    [5, 3, 1],
                    [0, 6, 3]])

y_pred = np.array([[3, 1, 1],
                    [5, 3, 1],
                    [0, 6, 3]])

print(y_pred)
print("-----------")
print(y_true)
print("-----------")
print("Moyenne Dice coef: ",dice_coeff_multiclass(y_pred, y_true))

[[3 1 1]
 [5 3 1]
 [0 6 3]]
-----------
[[3 1 1]
 [5 3 1]
 [0 6 3]]
-----------
Moyenne Dice coef:  1.0
