In [1]:
from tensorflow.keras import backend as K  # type: ignore
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' # delete alert message from Tensorflow
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array  # type: ignore
import numpy as np

2024-04-20 10:44:36.558339: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
import tensorflow.keras.backend as K

In [8]:
def DiceLoss(y_true, y_pred, smooth=1e-6):
    y_true = K.cast(y_true, 'float32')
    y_pred = K.cast(y_pred, 'float32')
    
    inputs = K.flatten(y_pred)
    targets = K.flatten(y_true)

    # Ajouter une dimension supplémentaire
    targets = K.expand_dims(targets, axis=-1)
    inputs = K.expand_dims(inputs, axis=-1)
    
    intersection = K.sum(targets * inputs)
    dice = (2*intersection + smooth) / (K.sum(targets) + K.sum(inputs) + smooth)

    return 1 - dice


In [19]:
y_true = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 1]])

y_pred = np.array([[0, 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]])

#y_pred = np.array([[1, 0, 0],
#                    [1, 1, 1],
 #                   [1, 1, 1]])

y_pred = np.array([[1, 0, 0],
                    [1, 1, 1],
                   [1, 1, 1]])

# Tester la fonction DiceLoss
loss = DiceLoss(y_true, y_pred)
print("Dice Loss:", loss)

Dice Loss: tf.Tensor(0.12500006, shape=(), dtype=float32)


In [18]:
import numpy as np
from sklearn.metrics import confusion_matrix

# Créer des matrices d'exemple pour l'image vérité terrain (ground truth) et la prédiction de segmentation
# Remarque : ceci est un exemple simplifié, assurez-vous d'utiliser des valeurs appropriées pour votre application
ground_truth = np.array([[0, 1, 1, 0],
                         [1, 2, 1, 0],
                         [1, 1, 1, 2]])

prediction = np.array([[0, 1, 1, 0],
                       [1, 1, 2, 0],
                       [1, 1, 1, 2]])

#######
ground_truth = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 1]])

prediction = np.array([[0, 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]])

######
prediction = np.array([[1, 0, 0],
                    [1, 1, 1],
                   [1, 1, 1]])

# Calculer la matrice de confusion
conf_matrix = confusion_matrix(ground_truth.flatten(), prediction.flatten())

# Calculer le score de Dice pour chaque classe
dice_scores = []
for i in range(conf_matrix.shape[0]):
    TP = conf_matrix[i, i]
    FP = np.sum(conf_matrix[:, i]) - TP
    FN = np.sum(conf_matrix[i, :]) - TP
    dice_score = 2 * TP / (2 * TP + FP + FN)
    dice_scores.append(dice_score)

# Afficher les scores de Dice pour chaque classe
for i, score in enumerate(dice_scores):
    print(f"Classe {i}: Score de Dice = {score}")

# Calculer le score de Dice moyen
mean_dice_score = np.mean(dice_scores)
print(f"Score de Dice moyen = {mean_dice_score}")


Classe 0: Score de Dice = 0.0
Classe 1: Score de Dice = 0.875
Score de Dice moyen = 0.4375


In [3]:
# Suppose arr est votre tableau numpy
import numpy as np
import tensorflow as tf

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Convertir le tableau en tenseur TensorFlow
tensor = tf.convert_to_tensor(arr)

# Afficher le tenseur
print("Tenseur TensorFlow :")
print(tensor)

2024-04-20 15:08:06.663994: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Tenseur TensorFlow :
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [4]:
test = tensor.numpy()
test

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
import tensorflow as tf
import numpy as np

# Suppose arr est votre tableau numpy
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Créer un tenseur symbolique avec la même forme que le tableau
placeholder_tensor = tf.placeholder(dtype=tf.float32, shape=arr.shape)

# Vous pouvez également spécifier le dtype si nécessaire, par exemple : tf.placeholder(dtype=tf.int32, shape=arr.shape)

# Utilisez le tenseur symbolique dans votre modèle TensorFlow
# Par exemple, en l'utilisant dans un calcul :
double_tensor = placeholder_tensor * 2

with tf.Session() as sess:
    # Alimentez le placeholder avec les données du tableau
    result = sess.run(double_tensor, feed_dict={placeholder_tensor: arr})
    print("Résultat du doublement du tenseur symbolique :")
    print(result)


AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [6]:
import tensorflow as tf
import numpy as np

# Suppose arr est votre tableau numpy
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Créer un tenseur TensorFlow à partir du tableau
tensor_symbolic = tf.constant(arr, dtype=tf.float32)

# Vous pouvez également spécifier le dtype si nécessaire, par exemple : tf.constant(arr, dtype=tf.int32)

# Utilisez le tenseur symbolique dans votre modèle TensorFlow
# Par exemple, en l'utilisant dans un calcul :
double_tensor = tensor_symbolic * 2

print("Résultat du doublement du tenseur symbolique :")
print(double_tensor.numpy())  # Convertir le tenseur en numpy array pour l'afficher


Résultat du doublement du tenseur symbolique :
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
